name: Coverage
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  job:
    runs-on: ubuntu-latest

    name: Coverage

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install programs
        run: |
          sudo apt install gcov

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov: true
