name: Linux
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  job:
    runs-on: ubuntu-latest

    name: Linux X64 buildShared=${{matrix.buildShared}}

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install CMake.
        uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: '${{github.workspace}}/vcpkg'
          vcpkgGitCommitId: 'fd1bdf6ad343e390a5d043b23f0022b3188b5ac2'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure CMake
        run: 'cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Ninja" 
          -DUTILS_BUILD_SHARED_LIBS=${{matrix.buildShared}} 
          -DUTILS_BUILD_TESTING=ON 
          -DUTILS_INSTALL=OFF 
          -DUTILS_BUILD_EXAMPLE=OFF 
          -DUTILS_GENERATE_DOCUMENTATION=OFF 
          -DUTILS_PEDANTIC=OFF 
          -DUTILS_WERROR=OFF 
          -DUTILS_ENABLE_COVERAGE=OFF 
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake'

      - name: Coverage
        uses: codecov/codecov-action@v3
