name: windows-tests
on: push
jobs:
  shedule:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - vcpkgCommitId: '253704407ae68efa37bf8f5b59b3e06dd40d3d3f'
          - cmakeConfigPreset: [ windows-x64-shared-md-vcpkg ]
          - cmakeBuildPreset: [ build-debug, build-release ]
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install CMake.
        uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
            vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
            vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
            vcpkgJsonGlob: '**/vcpkg.json'

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.cmakeConfigPreset }}
          buildPreset: ${{ matrix.cmakePreset }}
        
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows