name: windows-tests
on: push
jobs:
  Windows:
    runs-on: windows-latest

    strategy:
      matrix:
        buildType: [ 'static', 'shared' ]
        msvcRuntime: [ 'MD', 'MT' ]

    env:
      if: ${{matrix.buildType == 'static'}}
        buildSharedLibs: OFF
      if: ${{matrix.buildType == 'shared'}}
        buildSharedLibs: ON
      if: ${{matrix.msvcRuntime == 'MD'}}
        msvcStaticRuntime: OFF
      if: ${{matrix.msvcRuntime == 'MT'}}
        msvcStaticRuntime: ON

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install CMake.
        uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: '${{github.workspace}}/vcpkg'
          vcpkgGitCommitId: 'fd1bdf6ad343e390a5d043b23f0022b3188b5ac2'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure CMake
        run: 'cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -A x64 
          -DUTILS_BUILD_SHARED_LIBS=${{env.buildSharedLibs}} 
          -DUTILS_BUILD_TESTING=ON 
          -DUTILS_INSTALL=OFF 
          -DUTILS_BUILD_EXAMPLE=OFF 
          -DUTILS_GENERATE_DOCUMENTATION=OFF 
          -DUTILS_PEDANTIC=ON 
          -DUTILS_WERROR=ON 
          -DUTILS_MSVC_STATIC_RUNTIME=${{env.msvcStaticRuntime}} 
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake'

      - name: Build Debug
        run: 'cmake --build ${{github.workspace}}/build --config Debug'
        
      - name: Build Release
        run: 'cmake --build ${{github.workspace}}/build --config Release'
        
      - name: Test Debug
        working-directory: ${{github.workspace}}/build
        run: ctest -C Debug -VV
        
      - name: Test Release
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release -VV
        